// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chunk.proto

#ifndef PROTOBUF_INCLUDED_Chunk_2eproto
#define PROTOBUF_INCLUDED_Chunk_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Chunk_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Chunk_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Chunk_2eproto();
namespace ofs {
namespace c2m {
class BlockStatus;
class BlockStatusDefaultTypeInternal;
extern BlockStatusDefaultTypeInternal _BlockStatus_default_instance_;
class Lease;
class LeaseDefaultTypeInternal;
extern LeaseDefaultTypeInternal _Lease_default_instance_;
class RecoverInfo;
class RecoverInfoDefaultTypeInternal;
extern RecoverInfoDefaultTypeInternal _RecoverInfo_default_instance_;
class RegisterChunkServerRequest;
class RegisterChunkServerRequestDefaultTypeInternal;
extern RegisterChunkServerRequestDefaultTypeInternal _RegisterChunkServerRequest_default_instance_;
class RegisterChunkServerResponse;
class RegisterChunkServerResponseDefaultTypeInternal;
extern RegisterChunkServerResponseDefaultTypeInternal _RegisterChunkServerResponse_default_instance_;
class RenewLeaseRequest;
class RenewLeaseRequestDefaultTypeInternal;
extern RenewLeaseRequestDefaultTypeInternal _RenewLeaseRequest_default_instance_;
class RenewLeaseResponse;
class RenewLeaseResponseDefaultTypeInternal;
extern RenewLeaseResponseDefaultTypeInternal _RenewLeaseResponse_default_instance_;
class ReportRequest;
class ReportRequestDefaultTypeInternal;
extern ReportRequestDefaultTypeInternal _ReportRequest_default_instance_;
class ReportResponse;
class ReportResponseDefaultTypeInternal;
extern ReportResponseDefaultTypeInternal _ReportResponse_default_instance_;
}  // namespace c2m
}  // namespace ofs
namespace google {
namespace protobuf {
template<> ::ofs::c2m::BlockStatus* Arena::CreateMaybeMessage<::ofs::c2m::BlockStatus>(Arena*);
template<> ::ofs::c2m::Lease* Arena::CreateMaybeMessage<::ofs::c2m::Lease>(Arena*);
template<> ::ofs::c2m::RecoverInfo* Arena::CreateMaybeMessage<::ofs::c2m::RecoverInfo>(Arena*);
template<> ::ofs::c2m::RegisterChunkServerRequest* Arena::CreateMaybeMessage<::ofs::c2m::RegisterChunkServerRequest>(Arena*);
template<> ::ofs::c2m::RegisterChunkServerResponse* Arena::CreateMaybeMessage<::ofs::c2m::RegisterChunkServerResponse>(Arena*);
template<> ::ofs::c2m::RenewLeaseRequest* Arena::CreateMaybeMessage<::ofs::c2m::RenewLeaseRequest>(Arena*);
template<> ::ofs::c2m::RenewLeaseResponse* Arena::CreateMaybeMessage<::ofs::c2m::RenewLeaseResponse>(Arena*);
template<> ::ofs::c2m::ReportRequest* Arena::CreateMaybeMessage<::ofs::c2m::ReportRequest>(Arena*);
template<> ::ofs::c2m::ReportResponse* Arena::CreateMaybeMessage<::ofs::c2m::ReportResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ofs {
namespace c2m {

enum ErrorCode {
  EC_OK = 0,
  EC_BLOCK_CLEAN = 1,
  EC_BLOCK_RECOVER = 2,
  EC_BLOCK_NOT_EXIST = 3,
  EC_REPLICA_DO_NOT_HAS_LEASE = 4
};
bool ErrorCode_IsValid(int value);
const ErrorCode ErrorCode_MIN = EC_OK;
const ErrorCode ErrorCode_MAX = EC_REPLICA_DO_NOT_HAS_LEASE;
const int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor();
inline const ::std::string& ErrorCode_Name(ErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ErrorCode_descriptor(), value);
}
inline bool ErrorCode_Parse(
    const ::std::string& name, ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================

class RegisterChunkServerRequest :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.RegisterChunkServerRequest) */ {
 public:
  RegisterChunkServerRequest();
  virtual ~RegisterChunkServerRequest();

  RegisterChunkServerRequest(const RegisterChunkServerRequest& from);

  inline RegisterChunkServerRequest& operator=(const RegisterChunkServerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterChunkServerRequest(RegisterChunkServerRequest&& from) noexcept
    : RegisterChunkServerRequest() {
    *this = ::std::move(from);
  }

  inline RegisterChunkServerRequest& operator=(RegisterChunkServerRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RegisterChunkServerRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterChunkServerRequest* internal_default_instance() {
    return reinterpret_cast<const RegisterChunkServerRequest*>(
               &_RegisterChunkServerRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RegisterChunkServerRequest* other);
  friend void swap(RegisterChunkServerRequest& a, RegisterChunkServerRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterChunkServerRequest* New() const final {
    return CreateMaybeMessage<RegisterChunkServerRequest>(nullptr);
  }

  RegisterChunkServerRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RegisterChunkServerRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RegisterChunkServerRequest& from);
  void MergeFrom(const RegisterChunkServerRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterChunkServerRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string host = 2;
  bool has_host() const;
  void clear_host();
  static const int kHostFieldNumber = 2;
  const ::std::string& host() const;
  void set_host(const ::std::string& value);
  #if LANG_CXX11
  void set_host(::std::string&& value);
  #endif
  void set_host(const char* value);
  void set_host(const char* value, size_t size);
  ::std::string* mutable_host();
  ::std::string* release_host();
  void set_allocated_host(::std::string* host);

  // required string extend = 9;
  bool has_extend() const;
  void clear_extend();
  static const int kExtendFieldNumber = 9;
  const ::std::string& extend() const;
  void set_extend(const ::std::string& value);
  #if LANG_CXX11
  void set_extend(::std::string&& value);
  #endif
  void set_extend(const char* value);
  void set_extend(const char* value, size_t size);
  ::std::string* mutable_extend();
  ::std::string* release_extend();
  void set_allocated_extend(::std::string* extend);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required int32 port = 3;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 3;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // required int32 rack = 4;
  bool has_rack() const;
  void clear_rack();
  static const int kRackFieldNumber = 4;
  ::google::protobuf::int32 rack() const;
  void set_rack(::google::protobuf::int32 value);

  // required int32 dc = 5;
  bool has_dc() const;
  void clear_dc();
  static const int kDcFieldNumber = 5;
  ::google::protobuf::int32 dc() const;
  void set_dc(::google::protobuf::int32 value);

  // required int32 remain = 6;
  bool has_remain() const;
  void clear_remain();
  static const int kRemainFieldNumber = 6;
  ::google::protobuf::int32 remain() const;
  void set_remain(::google::protobuf::int32 value);

  // required bool fault = 7;
  bool has_fault() const;
  void clear_fault();
  static const int kFaultFieldNumber = 7;
  bool fault() const;
  void set_fault(bool value);

  // required int32 load = 8;
  bool has_load() const;
  void clear_load();
  static const int kLoadFieldNumber = 8;
  ::google::protobuf::int32 load() const;
  void set_load(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.RegisterChunkServerRequest)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr host_;
  ::google::protobuf::internal::ArenaStringPtr extend_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::int32 rack_;
  ::google::protobuf::int32 dc_;
  ::google::protobuf::int32 remain_;
  bool fault_;
  ::google::protobuf::int32 load_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class RegisterChunkServerResponse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.RegisterChunkServerResponse) */ {
 public:
  RegisterChunkServerResponse();
  virtual ~RegisterChunkServerResponse();

  RegisterChunkServerResponse(const RegisterChunkServerResponse& from);

  inline RegisterChunkServerResponse& operator=(const RegisterChunkServerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterChunkServerResponse(RegisterChunkServerResponse&& from) noexcept
    : RegisterChunkServerResponse() {
    *this = ::std::move(from);
  }

  inline RegisterChunkServerResponse& operator=(RegisterChunkServerResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RegisterChunkServerResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterChunkServerResponse* internal_default_instance() {
    return reinterpret_cast<const RegisterChunkServerResponse*>(
               &_RegisterChunkServerResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(RegisterChunkServerResponse* other);
  friend void swap(RegisterChunkServerResponse& a, RegisterChunkServerResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterChunkServerResponse* New() const final {
    return CreateMaybeMessage<RegisterChunkServerResponse>(nullptr);
  }

  RegisterChunkServerResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RegisterChunkServerResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RegisterChunkServerResponse& from);
  void MergeFrom(const RegisterChunkServerResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterChunkServerResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool ok = 1;
  bool has_ok() const;
  void clear_ok();
  static const int kOkFieldNumber = 1;
  bool ok() const;
  void set_ok(bool value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.RegisterChunkServerResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  bool ok_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class BlockStatus :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.BlockStatus) */ {
 public:
  BlockStatus();
  virtual ~BlockStatus();

  BlockStatus(const BlockStatus& from);

  inline BlockStatus& operator=(const BlockStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BlockStatus(BlockStatus&& from) noexcept
    : BlockStatus() {
    *this = ::std::move(from);
  }

  inline BlockStatus& operator=(BlockStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BlockStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BlockStatus* internal_default_instance() {
    return reinterpret_cast<const BlockStatus*>(
               &_BlockStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(BlockStatus* other);
  friend void swap(BlockStatus& a, BlockStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BlockStatus* New() const final {
    return CreateMaybeMessage<BlockStatus>(nullptr);
  }

  BlockStatus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BlockStatus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BlockStatus& from);
  void MergeFrom(const BlockStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlockStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // required int64 version = 2;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::int64 version() const;
  void set_version(::google::protobuf::int64 value);

  // required int32 size = 3;
  bool has_size() const;
  void clear_size();
  static const int kSizeFieldNumber = 3;
  ::google::protobuf::int32 size() const;
  void set_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.BlockStatus)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::int64 version_;
  ::google::protobuf::int32 size_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class ReportRequest :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.ReportRequest) */ {
 public:
  ReportRequest();
  virtual ~ReportRequest();

  ReportRequest(const ReportRequest& from);

  inline ReportRequest& operator=(const ReportRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReportRequest(ReportRequest&& from) noexcept
    : ReportRequest() {
    *this = ::std::move(from);
  }

  inline ReportRequest& operator=(ReportRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ReportRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReportRequest* internal_default_instance() {
    return reinterpret_cast<const ReportRequest*>(
               &_ReportRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ReportRequest* other);
  friend void swap(ReportRequest& a, ReportRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReportRequest* New() const final {
    return CreateMaybeMessage<ReportRequest>(nullptr);
  }

  ReportRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReportRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReportRequest& from);
  void MergeFrom(const ReportRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReportRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .ofs.c2m.BlockStatus blocks = 2;
  bool has_blocks() const;
  void clear_blocks();
  static const int kBlocksFieldNumber = 2;
  const ::ofs::c2m::BlockStatus& blocks() const;
  ::ofs::c2m::BlockStatus* release_blocks();
  ::ofs::c2m::BlockStatus* mutable_blocks();
  void set_allocated_blocks(::ofs::c2m::BlockStatus* blocks);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.ReportRequest)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::ofs::c2m::BlockStatus* blocks_;
  ::google::protobuf::int32 id_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class RecoverInfo :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.RecoverInfo) */ {
 public:
  RecoverInfo();
  virtual ~RecoverInfo();

  RecoverInfo(const RecoverInfo& from);

  inline RecoverInfo& operator=(const RecoverInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RecoverInfo(RecoverInfo&& from) noexcept
    : RecoverInfo() {
    *this = ::std::move(from);
  }

  inline RecoverInfo& operator=(RecoverInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RecoverInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RecoverInfo* internal_default_instance() {
    return reinterpret_cast<const RecoverInfo*>(
               &_RecoverInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(RecoverInfo* other);
  friend void swap(RecoverInfo& a, RecoverInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RecoverInfo* New() const final {
    return CreateMaybeMessage<RecoverInfo>(nullptr);
  }

  RecoverInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RecoverInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RecoverInfo& from);
  void MergeFrom(const RecoverInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecoverInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 chunkservers = 5;
  int chunkservers_size() const;
  void clear_chunkservers();
  static const int kChunkserversFieldNumber = 5;
  ::google::protobuf::int32 chunkservers(int index) const;
  void set_chunkservers(int index, ::google::protobuf::int32 value);
  void add_chunkservers(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      chunkservers() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_chunkservers();

  // required int64 until = 1;
  bool has_until() const;
  void clear_until();
  static const int kUntilFieldNumber = 1;
  ::google::protobuf::int64 until() const;
  void set_until(::google::protobuf::int64 value);

  // required int64 version = 2;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::int64 version() const;
  void set_version(::google::protobuf::int64 value);

  // required int64 newVersion = 3;
  bool has_newversion() const;
  void clear_newversion();
  static const int kNewVersionFieldNumber = 3;
  ::google::protobuf::int64 newversion() const;
  void set_newversion(::google::protobuf::int64 value);

  // required int32 copyTo = 4;
  bool has_copyto() const;
  void clear_copyto();
  static const int kCopyToFieldNumber = 4;
  ::google::protobuf::int32 copyto() const;
  void set_copyto(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.RecoverInfo)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > chunkservers_;
  ::google::protobuf::int64 until_;
  ::google::protobuf::int64 version_;
  ::google::protobuf::int64 newversion_;
  ::google::protobuf::int32 copyto_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class ReportResponse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.ReportResponse) */ {
 public:
  ReportResponse();
  virtual ~ReportResponse();

  ReportResponse(const ReportResponse& from);

  inline ReportResponse& operator=(const ReportResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReportResponse(ReportResponse&& from) noexcept
    : ReportResponse() {
    *this = ::std::move(from);
  }

  inline ReportResponse& operator=(ReportResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ReportResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReportResponse* internal_default_instance() {
    return reinterpret_cast<const ReportResponse*>(
               &_ReportResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ReportResponse* other);
  friend void swap(ReportResponse& a, ReportResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReportResponse* New() const final {
    return CreateMaybeMessage<ReportResponse>(nullptr);
  }

  ReportResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReportResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReportResponse& from);
  void MergeFrom(const ReportResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReportResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ofs.c2m.RecoverInfo recoverInfo = 2;
  bool has_recoverinfo() const;
  void clear_recoverinfo();
  static const int kRecoverInfoFieldNumber = 2;
  const ::ofs::c2m::RecoverInfo& recoverinfo() const;
  ::ofs::c2m::RecoverInfo* release_recoverinfo();
  ::ofs::c2m::RecoverInfo* mutable_recoverinfo();
  void set_allocated_recoverinfo(::ofs::c2m::RecoverInfo* recoverinfo);

  // required .ofs.c2m.ErrorCode errCode = 1;
  bool has_errcode() const;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 1;
  ::ofs::c2m::ErrorCode errcode() const;
  void set_errcode(::ofs::c2m::ErrorCode value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.ReportResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::ofs::c2m::RecoverInfo* recoverinfo_;
  int errcode_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class RenewLeaseRequest :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.RenewLeaseRequest) */ {
 public:
  RenewLeaseRequest();
  virtual ~RenewLeaseRequest();

  RenewLeaseRequest(const RenewLeaseRequest& from);

  inline RenewLeaseRequest& operator=(const RenewLeaseRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RenewLeaseRequest(RenewLeaseRequest&& from) noexcept
    : RenewLeaseRequest() {
    *this = ::std::move(from);
  }

  inline RenewLeaseRequest& operator=(RenewLeaseRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RenewLeaseRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RenewLeaseRequest* internal_default_instance() {
    return reinterpret_cast<const RenewLeaseRequest*>(
               &_RenewLeaseRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(RenewLeaseRequest* other);
  friend void swap(RenewLeaseRequest& a, RenewLeaseRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RenewLeaseRequest* New() const final {
    return CreateMaybeMessage<RenewLeaseRequest>(nullptr);
  }

  RenewLeaseRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RenewLeaseRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RenewLeaseRequest& from);
  void MergeFrom(const RenewLeaseRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RenewLeaseRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 blockId = 2;
  bool has_blockid() const;
  void clear_blockid();
  static const int kBlockIdFieldNumber = 2;
  ::google::protobuf::int64 blockid() const;
  void set_blockid(::google::protobuf::int64 value);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.RenewLeaseRequest)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 blockid_;
  ::google::protobuf::int32 id_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class Lease :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.Lease) */ {
 public:
  Lease();
  virtual ~Lease();

  Lease(const Lease& from);

  inline Lease& operator=(const Lease& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Lease(Lease&& from) noexcept
    : Lease() {
    *this = ::std::move(from);
  }

  inline Lease& operator=(Lease&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Lease& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Lease* internal_default_instance() {
    return reinterpret_cast<const Lease*>(
               &_Lease_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(Lease* other);
  friend void swap(Lease& a, Lease& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Lease* New() const final {
    return CreateMaybeMessage<Lease>(nullptr);
  }

  Lease* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Lease>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Lease& from);
  void MergeFrom(const Lease& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Lease* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 chunkservers = 4;
  int chunkservers_size() const;
  void clear_chunkservers();
  static const int kChunkserversFieldNumber = 4;
  ::google::protobuf::int32 chunkservers(int index) const;
  void set_chunkservers(int index, ::google::protobuf::int32 value);
  void add_chunkservers(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      chunkservers() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_chunkservers();

  // required int64 until = 1;
  bool has_until() const;
  void clear_until();
  static const int kUntilFieldNumber = 1;
  ::google::protobuf::int64 until() const;
  void set_until(::google::protobuf::int64 value);

  // required int64 version = 2;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::int64 version() const;
  void set_version(::google::protobuf::int64 value);

  // required int64 newVersion = 3;
  bool has_newversion() const;
  void clear_newversion();
  static const int kNewVersionFieldNumber = 3;
  ::google::protobuf::int64 newversion() const;
  void set_newversion(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.Lease)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > chunkservers_;
  ::google::protobuf::int64 until_;
  ::google::protobuf::int64 version_;
  ::google::protobuf::int64 newversion_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class RenewLeaseResponse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ofs.c2m.RenewLeaseResponse) */ {
 public:
  RenewLeaseResponse();
  virtual ~RenewLeaseResponse();

  RenewLeaseResponse(const RenewLeaseResponse& from);

  inline RenewLeaseResponse& operator=(const RenewLeaseResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RenewLeaseResponse(RenewLeaseResponse&& from) noexcept
    : RenewLeaseResponse() {
    *this = ::std::move(from);
  }

  inline RenewLeaseResponse& operator=(RenewLeaseResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RenewLeaseResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RenewLeaseResponse* internal_default_instance() {
    return reinterpret_cast<const RenewLeaseResponse*>(
               &_RenewLeaseResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(RenewLeaseResponse* other);
  friend void swap(RenewLeaseResponse& a, RenewLeaseResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RenewLeaseResponse* New() const final {
    return CreateMaybeMessage<RenewLeaseResponse>(nullptr);
  }

  RenewLeaseResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RenewLeaseResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RenewLeaseResponse& from);
  void MergeFrom(const RenewLeaseResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RenewLeaseResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ofs.c2m.Lease lease = 2;
  bool has_lease() const;
  void clear_lease();
  static const int kLeaseFieldNumber = 2;
  const ::ofs::c2m::Lease& lease() const;
  ::ofs::c2m::Lease* release_lease();
  ::ofs::c2m::Lease* mutable_lease();
  void set_allocated_lease(::ofs::c2m::Lease* lease);

  // required .ofs.c2m.ErrorCode errCode = 1;
  bool has_errcode() const;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 1;
  ::ofs::c2m::ErrorCode errcode() const;
  void set_errcode(::ofs::c2m::ErrorCode value);

  // @@protoc_insertion_point(class_scope:ofs.c2m.RenewLeaseResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::ofs::c2m::Lease* lease_;
  int errcode_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// ===================================================================

class OfsChunkService_Stub;

class OfsChunkService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline OfsChunkService() {};
 public:
  virtual ~OfsChunkService();

  typedef OfsChunkService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void RegisterChunkServer(::google::protobuf::RpcController* controller,
                       const ::ofs::c2m::RegisterChunkServerRequest* request,
                       ::ofs::c2m::RegisterChunkServerResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void Report(::google::protobuf::RpcController* controller,
                       const ::ofs::c2m::ReportRequest* request,
                       ::ofs::c2m::ReportResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void RenewLease(::google::protobuf::RpcController* controller,
                       const ::ofs::c2m::RenewLeaseRequest* request,
                       ::ofs::c2m::RenewLeaseResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(OfsChunkService);
};

class OfsChunkService_Stub : public OfsChunkService {
 public:
  OfsChunkService_Stub(::google::protobuf::RpcChannel* channel);
  OfsChunkService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~OfsChunkService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements OfsChunkService ------------------------------------------

  void RegisterChunkServer(::google::protobuf::RpcController* controller,
                       const ::ofs::c2m::RegisterChunkServerRequest* request,
                       ::ofs::c2m::RegisterChunkServerResponse* response,
                       ::google::protobuf::Closure* done);
  void Report(::google::protobuf::RpcController* controller,
                       const ::ofs::c2m::ReportRequest* request,
                       ::ofs::c2m::ReportResponse* response,
                       ::google::protobuf::Closure* done);
  void RenewLease(::google::protobuf::RpcController* controller,
                       const ::ofs::c2m::RenewLeaseRequest* request,
                       ::ofs::c2m::RenewLeaseResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(OfsChunkService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterChunkServerRequest

// required int32 id = 1;
inline bool RegisterChunkServerRequest::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegisterChunkServerRequest::clear_id() {
  id_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 RegisterChunkServerRequest::id() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.id)
  return id_;
}
inline void RegisterChunkServerRequest::set_id(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  id_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.id)
}

// required string host = 2;
inline bool RegisterChunkServerRequest::has_host() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterChunkServerRequest::clear_host() {
  host_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& RegisterChunkServerRequest::host() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.host)
  return host_.GetNoArena();
}
inline void RegisterChunkServerRequest::set_host(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  host_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.host)
}
#if LANG_CXX11
inline void RegisterChunkServerRequest::set_host(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  host_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ofs.c2m.RegisterChunkServerRequest.host)
}
#endif
inline void RegisterChunkServerRequest::set_host(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  host_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ofs.c2m.RegisterChunkServerRequest.host)
}
inline void RegisterChunkServerRequest::set_host(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  host_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ofs.c2m.RegisterChunkServerRequest.host)
}
inline ::std::string* RegisterChunkServerRequest::mutable_host() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:ofs.c2m.RegisterChunkServerRequest.host)
  return host_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterChunkServerRequest::release_host() {
  // @@protoc_insertion_point(field_release:ofs.c2m.RegisterChunkServerRequest.host)
  if (!has_host()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return host_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterChunkServerRequest::set_allocated_host(::std::string* host) {
  if (host != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  host_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), host);
  // @@protoc_insertion_point(field_set_allocated:ofs.c2m.RegisterChunkServerRequest.host)
}

// required int32 port = 3;
inline bool RegisterChunkServerRequest::has_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegisterChunkServerRequest::clear_port() {
  port_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 RegisterChunkServerRequest::port() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.port)
  return port_;
}
inline void RegisterChunkServerRequest::set_port(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  port_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.port)
}

// required int32 rack = 4;
inline bool RegisterChunkServerRequest::has_rack() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegisterChunkServerRequest::clear_rack() {
  rack_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::int32 RegisterChunkServerRequest::rack() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.rack)
  return rack_;
}
inline void RegisterChunkServerRequest::set_rack(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  rack_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.rack)
}

// required int32 dc = 5;
inline bool RegisterChunkServerRequest::has_dc() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RegisterChunkServerRequest::clear_dc() {
  dc_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::int32 RegisterChunkServerRequest::dc() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.dc)
  return dc_;
}
inline void RegisterChunkServerRequest::set_dc(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  dc_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.dc)
}

// required int32 remain = 6;
inline bool RegisterChunkServerRequest::has_remain() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RegisterChunkServerRequest::clear_remain() {
  remain_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::google::protobuf::int32 RegisterChunkServerRequest::remain() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.remain)
  return remain_;
}
inline void RegisterChunkServerRequest::set_remain(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000040u;
  remain_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.remain)
}

// required bool fault = 7;
inline bool RegisterChunkServerRequest::has_fault() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RegisterChunkServerRequest::clear_fault() {
  fault_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool RegisterChunkServerRequest::fault() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.fault)
  return fault_;
}
inline void RegisterChunkServerRequest::set_fault(bool value) {
  _has_bits_[0] |= 0x00000080u;
  fault_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.fault)
}

// required int32 load = 8;
inline bool RegisterChunkServerRequest::has_load() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RegisterChunkServerRequest::clear_load() {
  load_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::google::protobuf::int32 RegisterChunkServerRequest::load() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.load)
  return load_;
}
inline void RegisterChunkServerRequest::set_load(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  load_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.load)
}

// required string extend = 9;
inline bool RegisterChunkServerRequest::has_extend() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterChunkServerRequest::clear_extend() {
  extend_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& RegisterChunkServerRequest::extend() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerRequest.extend)
  return extend_.GetNoArena();
}
inline void RegisterChunkServerRequest::set_extend(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerRequest.extend)
}
#if LANG_CXX11
inline void RegisterChunkServerRequest::set_extend(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  extend_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ofs.c2m.RegisterChunkServerRequest.extend)
}
#endif
inline void RegisterChunkServerRequest::set_extend(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ofs.c2m.RegisterChunkServerRequest.extend)
}
inline void RegisterChunkServerRequest::set_extend(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ofs.c2m.RegisterChunkServerRequest.extend)
}
inline ::std::string* RegisterChunkServerRequest::mutable_extend() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:ofs.c2m.RegisterChunkServerRequest.extend)
  return extend_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterChunkServerRequest::release_extend() {
  // @@protoc_insertion_point(field_release:ofs.c2m.RegisterChunkServerRequest.extend)
  if (!has_extend()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return extend_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterChunkServerRequest::set_allocated_extend(::std::string* extend) {
  if (extend != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  extend_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), extend);
  // @@protoc_insertion_point(field_set_allocated:ofs.c2m.RegisterChunkServerRequest.extend)
}

// -------------------------------------------------------------------

// RegisterChunkServerResponse

// required bool ok = 1;
inline bool RegisterChunkServerResponse::has_ok() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterChunkServerResponse::clear_ok() {
  ok_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool RegisterChunkServerResponse::ok() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RegisterChunkServerResponse.ok)
  return ok_;
}
inline void RegisterChunkServerResponse::set_ok(bool value) {
  _has_bits_[0] |= 0x00000001u;
  ok_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RegisterChunkServerResponse.ok)
}

// -------------------------------------------------------------------

// BlockStatus

// required int64 id = 1;
inline bool BlockStatus::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BlockStatus::clear_id() {
  id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 BlockStatus::id() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.BlockStatus.id)
  return id_;
}
inline void BlockStatus::set_id(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  id_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.BlockStatus.id)
}

// required int64 version = 2;
inline bool BlockStatus::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BlockStatus::clear_version() {
  version_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 BlockStatus::version() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.BlockStatus.version)
  return version_;
}
inline void BlockStatus::set_version(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  version_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.BlockStatus.version)
}

// required int32 size = 3;
inline bool BlockStatus::has_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BlockStatus::clear_size() {
  size_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 BlockStatus::size() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.BlockStatus.size)
  return size_;
}
inline void BlockStatus::set_size(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  size_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.BlockStatus.size)
}

// -------------------------------------------------------------------

// ReportRequest

// required int32 id = 1;
inline bool ReportRequest::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReportRequest::clear_id() {
  id_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 ReportRequest::id() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.ReportRequest.id)
  return id_;
}
inline void ReportRequest::set_id(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  id_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.ReportRequest.id)
}

// required .ofs.c2m.BlockStatus blocks = 2;
inline bool ReportRequest::has_blocks() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReportRequest::clear_blocks() {
  if (blocks_ != nullptr) blocks_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::ofs::c2m::BlockStatus& ReportRequest::blocks() const {
  const ::ofs::c2m::BlockStatus* p = blocks_;
  // @@protoc_insertion_point(field_get:ofs.c2m.ReportRequest.blocks)
  return p != nullptr ? *p : *reinterpret_cast<const ::ofs::c2m::BlockStatus*>(
      &::ofs::c2m::_BlockStatus_default_instance_);
}
inline ::ofs::c2m::BlockStatus* ReportRequest::release_blocks() {
  // @@protoc_insertion_point(field_release:ofs.c2m.ReportRequest.blocks)
  _has_bits_[0] &= ~0x00000001u;
  ::ofs::c2m::BlockStatus* temp = blocks_;
  blocks_ = nullptr;
  return temp;
}
inline ::ofs::c2m::BlockStatus* ReportRequest::mutable_blocks() {
  _has_bits_[0] |= 0x00000001u;
  if (blocks_ == nullptr) {
    auto* p = CreateMaybeMessage<::ofs::c2m::BlockStatus>(GetArenaNoVirtual());
    blocks_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ofs.c2m.ReportRequest.blocks)
  return blocks_;
}
inline void ReportRequest::set_allocated_blocks(::ofs::c2m::BlockStatus* blocks) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete blocks_;
  }
  if (blocks) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      blocks = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, blocks, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  blocks_ = blocks;
  // @@protoc_insertion_point(field_set_allocated:ofs.c2m.ReportRequest.blocks)
}

// -------------------------------------------------------------------

// RecoverInfo

// required int64 until = 1;
inline bool RecoverInfo::has_until() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RecoverInfo::clear_until() {
  until_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 RecoverInfo::until() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RecoverInfo.until)
  return until_;
}
inline void RecoverInfo::set_until(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  until_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RecoverInfo.until)
}

// required int64 version = 2;
inline bool RecoverInfo::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RecoverInfo::clear_version() {
  version_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 RecoverInfo::version() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RecoverInfo.version)
  return version_;
}
inline void RecoverInfo::set_version(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  version_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RecoverInfo.version)
}

// required int64 newVersion = 3;
inline bool RecoverInfo::has_newversion() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RecoverInfo::clear_newversion() {
  newversion_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 RecoverInfo::newversion() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RecoverInfo.newVersion)
  return newversion_;
}
inline void RecoverInfo::set_newversion(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  newversion_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RecoverInfo.newVersion)
}

// required int32 copyTo = 4;
inline bool RecoverInfo::has_copyto() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RecoverInfo::clear_copyto() {
  copyto_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 RecoverInfo::copyto() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RecoverInfo.copyTo)
  return copyto_;
}
inline void RecoverInfo::set_copyto(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  copyto_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RecoverInfo.copyTo)
}

// repeated int32 chunkservers = 5;
inline int RecoverInfo::chunkservers_size() const {
  return chunkservers_.size();
}
inline void RecoverInfo::clear_chunkservers() {
  chunkservers_.Clear();
}
inline ::google::protobuf::int32 RecoverInfo::chunkservers(int index) const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RecoverInfo.chunkservers)
  return chunkservers_.Get(index);
}
inline void RecoverInfo::set_chunkservers(int index, ::google::protobuf::int32 value) {
  chunkservers_.Set(index, value);
  // @@protoc_insertion_point(field_set:ofs.c2m.RecoverInfo.chunkservers)
}
inline void RecoverInfo::add_chunkservers(::google::protobuf::int32 value) {
  chunkservers_.Add(value);
  // @@protoc_insertion_point(field_add:ofs.c2m.RecoverInfo.chunkservers)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
RecoverInfo::chunkservers() const {
  // @@protoc_insertion_point(field_list:ofs.c2m.RecoverInfo.chunkservers)
  return chunkservers_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
RecoverInfo::mutable_chunkservers() {
  // @@protoc_insertion_point(field_mutable_list:ofs.c2m.RecoverInfo.chunkservers)
  return &chunkservers_;
}

// -------------------------------------------------------------------

// ReportResponse

// required .ofs.c2m.ErrorCode errCode = 1;
inline bool ReportResponse::has_errcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReportResponse::clear_errcode() {
  errcode_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::ofs::c2m::ErrorCode ReportResponse::errcode() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.ReportResponse.errCode)
  return static_cast< ::ofs::c2m::ErrorCode >(errcode_);
}
inline void ReportResponse::set_errcode(::ofs::c2m::ErrorCode value) {
  assert(::ofs::c2m::ErrorCode_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  errcode_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.ReportResponse.errCode)
}

// optional .ofs.c2m.RecoverInfo recoverInfo = 2;
inline bool ReportResponse::has_recoverinfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReportResponse::clear_recoverinfo() {
  if (recoverinfo_ != nullptr) recoverinfo_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::ofs::c2m::RecoverInfo& ReportResponse::recoverinfo() const {
  const ::ofs::c2m::RecoverInfo* p = recoverinfo_;
  // @@protoc_insertion_point(field_get:ofs.c2m.ReportResponse.recoverInfo)
  return p != nullptr ? *p : *reinterpret_cast<const ::ofs::c2m::RecoverInfo*>(
      &::ofs::c2m::_RecoverInfo_default_instance_);
}
inline ::ofs::c2m::RecoverInfo* ReportResponse::release_recoverinfo() {
  // @@protoc_insertion_point(field_release:ofs.c2m.ReportResponse.recoverInfo)
  _has_bits_[0] &= ~0x00000001u;
  ::ofs::c2m::RecoverInfo* temp = recoverinfo_;
  recoverinfo_ = nullptr;
  return temp;
}
inline ::ofs::c2m::RecoverInfo* ReportResponse::mutable_recoverinfo() {
  _has_bits_[0] |= 0x00000001u;
  if (recoverinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::ofs::c2m::RecoverInfo>(GetArenaNoVirtual());
    recoverinfo_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ofs.c2m.ReportResponse.recoverInfo)
  return recoverinfo_;
}
inline void ReportResponse::set_allocated_recoverinfo(::ofs::c2m::RecoverInfo* recoverinfo) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete recoverinfo_;
  }
  if (recoverinfo) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      recoverinfo = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, recoverinfo, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  recoverinfo_ = recoverinfo;
  // @@protoc_insertion_point(field_set_allocated:ofs.c2m.ReportResponse.recoverInfo)
}

// -------------------------------------------------------------------

// RenewLeaseRequest

// required int32 id = 1;
inline bool RenewLeaseRequest::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RenewLeaseRequest::clear_id() {
  id_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 RenewLeaseRequest::id() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RenewLeaseRequest.id)
  return id_;
}
inline void RenewLeaseRequest::set_id(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  id_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RenewLeaseRequest.id)
}

// required int64 blockId = 2;
inline bool RenewLeaseRequest::has_blockid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RenewLeaseRequest::clear_blockid() {
  blockid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 RenewLeaseRequest::blockid() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RenewLeaseRequest.blockId)
  return blockid_;
}
inline void RenewLeaseRequest::set_blockid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  blockid_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RenewLeaseRequest.blockId)
}

// -------------------------------------------------------------------

// Lease

// required int64 until = 1;
inline bool Lease::has_until() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Lease::clear_until() {
  until_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 Lease::until() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.Lease.until)
  return until_;
}
inline void Lease::set_until(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  until_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.Lease.until)
}

// required int64 version = 2;
inline bool Lease::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Lease::clear_version() {
  version_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 Lease::version() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.Lease.version)
  return version_;
}
inline void Lease::set_version(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  version_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.Lease.version)
}

// required int64 newVersion = 3;
inline bool Lease::has_newversion() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Lease::clear_newversion() {
  newversion_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 Lease::newversion() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.Lease.newVersion)
  return newversion_;
}
inline void Lease::set_newversion(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  newversion_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.Lease.newVersion)
}

// repeated int32 chunkservers = 4;
inline int Lease::chunkservers_size() const {
  return chunkservers_.size();
}
inline void Lease::clear_chunkservers() {
  chunkservers_.Clear();
}
inline ::google::protobuf::int32 Lease::chunkservers(int index) const {
  // @@protoc_insertion_point(field_get:ofs.c2m.Lease.chunkservers)
  return chunkservers_.Get(index);
}
inline void Lease::set_chunkservers(int index, ::google::protobuf::int32 value) {
  chunkservers_.Set(index, value);
  // @@protoc_insertion_point(field_set:ofs.c2m.Lease.chunkservers)
}
inline void Lease::add_chunkservers(::google::protobuf::int32 value) {
  chunkservers_.Add(value);
  // @@protoc_insertion_point(field_add:ofs.c2m.Lease.chunkservers)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Lease::chunkservers() const {
  // @@protoc_insertion_point(field_list:ofs.c2m.Lease.chunkservers)
  return chunkservers_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Lease::mutable_chunkservers() {
  // @@protoc_insertion_point(field_mutable_list:ofs.c2m.Lease.chunkservers)
  return &chunkservers_;
}

// -------------------------------------------------------------------

// RenewLeaseResponse

// required .ofs.c2m.ErrorCode errCode = 1;
inline bool RenewLeaseResponse::has_errcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RenewLeaseResponse::clear_errcode() {
  errcode_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::ofs::c2m::ErrorCode RenewLeaseResponse::errcode() const {
  // @@protoc_insertion_point(field_get:ofs.c2m.RenewLeaseResponse.errCode)
  return static_cast< ::ofs::c2m::ErrorCode >(errcode_);
}
inline void RenewLeaseResponse::set_errcode(::ofs::c2m::ErrorCode value) {
  assert(::ofs::c2m::ErrorCode_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  errcode_ = value;
  // @@protoc_insertion_point(field_set:ofs.c2m.RenewLeaseResponse.errCode)
}

// optional .ofs.c2m.Lease lease = 2;
inline bool RenewLeaseResponse::has_lease() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RenewLeaseResponse::clear_lease() {
  if (lease_ != nullptr) lease_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::ofs::c2m::Lease& RenewLeaseResponse::lease() const {
  const ::ofs::c2m::Lease* p = lease_;
  // @@protoc_insertion_point(field_get:ofs.c2m.RenewLeaseResponse.lease)
  return p != nullptr ? *p : *reinterpret_cast<const ::ofs::c2m::Lease*>(
      &::ofs::c2m::_Lease_default_instance_);
}
inline ::ofs::c2m::Lease* RenewLeaseResponse::release_lease() {
  // @@protoc_insertion_point(field_release:ofs.c2m.RenewLeaseResponse.lease)
  _has_bits_[0] &= ~0x00000001u;
  ::ofs::c2m::Lease* temp = lease_;
  lease_ = nullptr;
  return temp;
}
inline ::ofs::c2m::Lease* RenewLeaseResponse::mutable_lease() {
  _has_bits_[0] |= 0x00000001u;
  if (lease_ == nullptr) {
    auto* p = CreateMaybeMessage<::ofs::c2m::Lease>(GetArenaNoVirtual());
    lease_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ofs.c2m.RenewLeaseResponse.lease)
  return lease_;
}
inline void RenewLeaseResponse::set_allocated_lease(::ofs::c2m::Lease* lease) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete lease_;
  }
  if (lease) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      lease = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, lease, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  lease_ = lease;
  // @@protoc_insertion_point(field_set_allocated:ofs.c2m.RenewLeaseResponse.lease)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace c2m
}  // namespace ofs

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ofs::c2m::ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ofs::c2m::ErrorCode>() {
  return ::ofs::c2m::ErrorCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Chunk_2eproto
